import Nav from "@/components/Nav";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Playfair_Display } from "next/font/google";
import ClientMessageDisplay from "./ClientMessageDisplay";
import Footer from "@/components/Footer";

const font = Playfair_Display({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-alabaster ${font.className} flex h-screen w-screen flex-col`}
      >
        <ClientMessageDisplay />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
